server:
  httpPort: 11111
  discoveryPort: 32227
mqtt:
  enabled: false
  autoConnect: true
  host: localhost
  port: 1883
  username: ""
  password: ""
  baseTopic: alpaca/safetymonitor
  clientId: alpaca-safety-monitor
logging:
  level: info
  maxLogEntries: 1000
